---
- name: "Change password on pmra user"
  hosts: hosts_to_configure 
  gather_facts: True
  become: True
  vars_files:
    - user.yml
  tasks:
    - name: "Change password"
      ansible.builtin.user:
        name: "{{ item.username }}"
        state: present
        password: "{{ item.pass | password_hash('sha512') }}"
      no_log: True
      loop: "{{ users }}"
